<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateGoodCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('good_categories', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 50)->default('');
            $table->unsignedInteger('pid')->default(0);
            $table->string('image', 255)->default('');
            $table->tinyInteger('status')->default(0);
            $table->unsignedInteger('sort')->default(0);
            $table->softDeletes();
            $table->nullableTimestamps();

            $table->index('pid', 'idx_pid');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('good_categories');
    }
}
